# Generated by Django 4.2 on 2024-03-29 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('size', models.TextField()),
                ('model', models.TextField()),
                ('status', models.TextField()),
                ('cutPath', models.TextField()),
                ('backgroundPath', models.TextField()),
                ('imgsArray', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
